apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-app
  labels:
    app: api-gateway-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-app
  template:
    metadata: 
      labels:
        app: api-gateway-app
    spec:
      containers:
        - name: api-gateway-app
          image: edyzar/api-gateway:0.0.1
          imagePullPolicy: Always
          ports:
           - containerPort: 8083

---

apiVersion: v1
kind: Service
metadata:
  name: api-gateway-svc
spec:
  selector:
    app: api-gateway-app
  ports:
    - port: 80
      targetPort: 8083
      protocol: TCP
