apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-service-app
  labels:
    app: book-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-service-app
  template:
    metadata: 
      labels:
        app: book-service-app
    spec:
      containers:
        - name: book-service-app
          image: edyzar/book-service:0.0.1
          imagePullPolicy: Always
          ports:
           - containerPort: 8084
          env: 
          - name: DB_HOST
            valueFrom: 
              configMapKeyRef:
                name: db-book-conf
                key: host
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: db-book-conf
                key: name
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-book-credentials
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-book-credentials
                key: password 

---

apiVersion: v1
kind: Service
metadata:
  name: book-service-svc
spec:
  selector:
    app: book-service-app
  ports:
    - port: 80
      targetPort: 8084
