apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-app
  labels:
    app: user-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service-app
  template:
    metadata: 
      labels:
        app: user-service-app
    spec:
      containers:
        - name: user-service-app
          image: edyzar/user-service:0.0.1
          imagePullPolicy: Always
          ports:
           - containerPort: 8082
          env: 
          - name: DB_HOST
            valueFrom: 
              configMapKeyRef:
                name: db-user-conf
                key: host
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: db-user-conf
                key: name
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-user-credentials
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-user-credentials
                key: password 

---

apiVersion: v1
kind: Service
metadata:
  name: user-service-svc
spec:
  selector:
    app: user-service-app
  ports:
    - port: 80
      targetPort: 8082
